version: "3.9"

services:
  db:
    image: postgres:15-alpine   # <-- Ð±Ñ‹Ð»Ð¾ 16.x
    environment:
      POSTGRES_DB: trainer_db
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: trainer
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: trainer_backend
    environment:
      # Ð­Ñ‚Ð¸ Ð¿ÐµÑ€ÐµÐ¼ÐµÐ½Ð½Ñ‹Ðµ Ð¿Ð¾Ð´Ñ…Ð²Ð°Ñ‚Ð¸Ñ‚ Spring
      DB_URL: jdbc:postgresql://db:5432/trainer_db
      DB_USER: trainer
      DB_PASS: trainer
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      # ðŸ”¹ persist Ð´Ð»Ñ Ð·Ð°Ð³Ñ€ÑƒÐ¶ÐµÐ½Ð½Ñ‹Ñ… Ñ„Ð°Ð¹Ð»Ð¾Ð² (Ñ„Ð¾Ñ‚Ð¾ Ð¿Ñ€Ð¾Ñ„Ð¸Ð»Ñ Ð¸ Ñ‚.Ð¿.)
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: trainer_frontend
    depends_on:
      - backend
    ports:
      - "5173:80" # ÑÐ°Ð¹Ñ‚ Ð±ÑƒÐ´ÐµÑ‚ Ð½Ð° http://localhost:5173

volumes:
  pg_data:
